idf_component_register(
    SRCS
        "embers_main.c"
        "nvs_storage.c"
        "wifi_sta.c"
        "captive_portal.c"
        "dns_hijack.c"
        "mdns_hub.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        lwip
        freertos
        esp_timer
        espressif__mdns
)
