#pragma once

/* portal_page.h — Self-contained captive-portal setup page.
 * Single C string literal. No external dependencies.
 * Keep under 8 KB. Served by captive_portal.c GET / handler.
 */

static const char PORTAL_PAGE_HTML[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>Embers Setup</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:system-ui,sans-serif;background:#111;color:#eee;"
"     display:flex;align-items:center;justify-content:center;"
"     min-height:100vh;padding:1rem}"
".card{background:#1e1e1e;border:1px solid #333;border-radius:12px;"
"      padding:2rem;width:100%;max-width:420px}"
"h1{font-size:1.4rem;margin-bottom:.25rem;color:#ff7f2a}"
".sub{font-size:.85rem;color:#888;margin-bottom:1.5rem}"
"label{display:block;font-size:.85rem;color:#aaa;margin-bottom:.3rem}"
"select,input{width:100%;padding:.6rem .8rem;background:#2a2a2a;"
"             border:1px solid #444;border-radius:6px;color:#eee;"
"             font-size:1rem;margin-bottom:1rem}"
"button{width:100%;padding:.75rem;background:#ff7f2a;border:none;"
"       border-radius:6px;color:#fff;font-size:1rem;cursor:pointer;"
"       font-weight:600;margin-top:.5rem}"
"button:disabled{background:#555;cursor:default}"
"#status{margin-top:1rem;font-size:.9rem;min-height:1.2em;text-align:center}"
".err{color:#f55}.ok{color:#5f5}"
"#scan-btn{background:#333;margin-bottom:1rem;margin-top:0;font-weight:400}"
"</style>"
"</head>"
"<body>"
"<div class=\"card\">"
"  <h1>Embers Setup</h1>"
"  <p class=\"sub\">Connect this device to your WiFi network.</p>"
"  <button id=\"scan-btn\" onclick=\"doScan()\">&#x21BA; Scan for networks</button>"
"  <label for=\"ssid-sel\">Network (SSID)</label>"
"  <select id=\"ssid-sel\" onchange=\"onSelChange()\">"
"    <option value=\"\">&#x2014; press Scan &#x2014;</option>"
"  </select>"
"  <label for=\"ssid-man\">Or type SSID manually</label>"
"  <input id=\"ssid-man\" type=\"text\" maxlength=\"32\" placeholder=\"Network name\">"
"  <label for=\"pass\">Password (leave blank for open networks)</label>"
"  <input id=\"pass\" type=\"password\" maxlength=\"63\" placeholder=\"Password\">"
"  <button id=\"save-btn\" onclick=\"doSave()\">Save &amp; Connect</button>"
"  <div id=\"status\"></div>"
"</div>"
"<script>"
"function setStatus(msg,cls){var s=document.getElementById('status');"
"  s.textContent=msg;s.className=cls||'';}"
"function ssid(){var m=document.getElementById('ssid-man').value.trim();"
"  if(m)return m;"
"  return document.getElementById('ssid-sel').value;}"
"function onSelChange(){"
"  var s=document.getElementById('ssid-sel');"
"  if(s.value)document.getElementById('ssid-man').value='';}"
"function doScan(){"
"  setStatus('Scanning\u2026','');"
"  var b=document.getElementById('scan-btn');b.disabled=true;"
"  fetch('/scan').then(function(r){return r.json();})"
"  .then(function(d){"
"    var sel=document.getElementById('ssid-sel');"
"    sel.innerHTML='<option value=\"\">&#x2014; select &#x2014;</option>';"
"    (d.networks||[]).forEach(function(n){"
"      var o=document.createElement('option');o.value=n.ssid;"
"      o.textContent=n.ssid+' ('+n.rssi+' dBm'+(n.auth?' \xF0\x9F\x94\x92':' open')+')';"
"      sel.appendChild(o);});"
"    setStatus('Found '+(d.networks||[]).length+' network(s).','ok');"
"  }).catch(function(){setStatus('Scan failed. Try again.','err');})"
"  .finally(function(){b.disabled=false;});}"
"function doSave(){"
"  var s=ssid(),p=document.getElementById('pass').value;"
"  if(!s){setStatus('Please enter or select an SSID.','err');return;}"
"  setStatus('Saving\u2026','');"
"  var b=document.getElementById('save-btn');b.disabled=true;"
"  var body='ssid='+encodeURIComponent(s)+'&pass='+encodeURIComponent(p);"
"  fetch('/save',{method:'POST',"
"    headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body})"
"  .then(function(r){return r.text().then(function(t){return{ok:r.ok,text:t};});})"
"  .then(function(res){"
"    if(res.ok){setStatus(res.text,'ok');}"
"    else{setStatus('Error: '+res.text,'err');b.disabled=false;}"
"  }).catch(function(){setStatus('Request failed.','err');b.disabled=false;});}"
"</script>"
"</body>"
"</html>";
